modLoader="javafml"
loaderVersion="[36,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="rats_expansion"
version="1.0.0"
displayName="Rats: Expansion"
credits="Vem Lavar a Louca Gamers - https://vemlavaralouca.com.br/about"
displayURL="https://github.com/VemLavarALoucaGamers/rats_expansion"
logoFile="logo.png"
authors="Tonhao Santos"
description='''
This mod adds extra things to the Rats mod
'''

[[dependencies.rats_expansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.rats_expansion]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

